### ISSUE TITLE
App breaks when enter input in swap page without connecting wallet

### ISSUE THREAD

**Issue by abstract829** [soroswap/frontend#202]
![Captura de pantalla 2023-11-20 a la(s) 10 29 24](https://github.com/soroswap/frontend/assets/56497105/eb429318-dd46-4c5e-b5ae-fae297aaa634)

**Comment by abstract829** [comment]
now inputs are disabled if no token is selected

https://github.com/soroswap/frontend/assets/56497105/a607535e-8981-42d6-ae2e-6cb1eb450fec

**Comment by joaquinsoza** [comment]
If there are two tokens selected but there is not liquidity for that pair it will let you type an amount in the second input but not in the first input... shouldn't it just let you type anything but the button show "Insufficient Liquidity" or not let you type on any of the inputs

**Comment by esteblock** [comment]
@abstract829 the comment of @joaquinsoza still happens when one of the tokens is a stellar classic asset.

**Comment by joaquinsoza** [comment]
Currently you can enter an amount only on the second input when tokens are selected.


![Image](https://github.com/soroswap/frontend/assets/34905663/4df1379a-b177-4606-b453-eefdde62e8b4)

### Expected behavior:

When not connected to a wallet, it should let you enter values to any of the inputs only if tokens are selected but the button should never say something else other than "Connect Wallet" currently if the pair doesnt exist it changes to "Route not found".


### Another Error

When a pair doesnt exist and it shows "Route not found" in the button (also when not connected with the wallet) if you click the button it shows you the Connect wallet modal and after trying to connect it shows this error

![Image](https://github.com/soroswap/frontend/assets/34905663/9600f622-58f6-466c-a31b-c96a70cf2668)

only if clicking on the "Route not found" button, it should align with the previous expected behavior... it should not even show you the "Route not found" text
