### ISSUE TITLE
user balance below the token selector

### ISSUE THREAD

**Issue by joaquinsoza** [soroswap/frontend#63]
selectedCurrencyBalance const is hardcoded to 1000 there is commented code on what it should do

```ts
  const selectedCurrencyBalance = 1000 //useFormattedTokenBalance(currency?.token_address, address)
```

if useFormattedTokenBalance is used, when you connect the wallet immediately after loading the website it shows an error... this should be fixed

file 
```
src/components/currencyInputPanel/SwapCurrencyInputPanel.tsx
```

max button should also work and set the input amount to the max possible amount, if its XLM it should count for the fees

**Comment by jtschuwirth** [comment]
i fixed the issue with the modal crashing the app if it is opened after the wallet is connected, for this i had to change de useTokenBalances because as it was calling hooks inside a map that was giving the issue, so i made the call to get the balances inside the row of CurrenciesList, because of this i had to remove the sorting of the currencies by balance.
